-- drop_tables.sql

DROP TABLE IF EXISTS HotelChain CASCADE;
DROP TABLE IF EXISTS HotelChainPhoneNumber CASCADE;
DROP TABLE IF EXISTS HotelChainEmailAddress CASCADE;
DROP TABLE IF EXISTS Hotel CASCADE;
DROP TABLE IF EXISTS Room CASCADE;
DROP TABLE IF EXISTS RoomIssue CASCADE;
DROP TABLE IF EXISTS Amenity CASCADE;
DROP TABLE IF EXISTS RoomAmenityJoin CASCADE;
DROP TABLE IF EXISTS Employee CASCADE;
DROP TABLE IF EXISTS Position CASCADE;
DROP TABLE IF EXISTS EmployeePositionJoin CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Archive CASCADE;
